--liquibase formatted sql
--changeset cosmic:world-default-character-settings
INSERT INTO setting_catalog
(setting_key,display_name,category,description,value_type,default_value,origin_type,source_file,source_symbol,implementation_files,apply_mode,compatibility,compatibility_note,scope_type,risk_level,min_value,max_value,sort_order)
VALUES
('server.world.defaultGmLevel','Default new-character GM level','Worlds & Channels','Default access level assigned only when a new character is created in this world. Existing characters are not changed.','INTEGER','0','YAML_EXISTING','config.yaml','worlds[].default_gm_level','src/main/java/config/WorldConfig.java; src/main/java/client/creator/CharacterFactory.java; src/main/java/server/configuration/ServerConfigurationOverrides.java','RESTART','SERVER_ONLY','High values are dangerous on public worlds. Keep public registration worlds at 0 unless account creation is locked down.','WORLD','HIGH',0,6,515),
('server.world.defaultEquipSlots','Default EQUIP slots','Worlds & Channels','Default EQUIP inventory slots assigned only when a new character is created in this world. Existing characters are not changed.','INTEGER','24','YAML_EXISTING','config.yaml','worlds[].default_equip_slots','src/main/java/config/WorldConfig.java; src/main/java/client/Character.java; src/main/java/server/configuration/ServerConfigurationOverrides.java','RESTART','SERVER_ONLY','Client-safe inventory slot cap is 96.','WORLD','MEDIUM',4,96,516),
('server.world.defaultUseSlots','Default USE slots','Worlds & Channels','Default USE inventory slots assigned only when a new character is created in this world. Existing characters are not changed.','INTEGER','24','YAML_EXISTING','config.yaml','worlds[].default_use_slots','src/main/java/config/WorldConfig.java; src/main/java/client/Character.java; src/main/java/server/configuration/ServerConfigurationOverrides.java','RESTART','SERVER_ONLY','Client-safe inventory slot cap is 96.','WORLD','MEDIUM',4,96,517),
('server.world.defaultSetupSlots','Default SETUP slots','Worlds & Channels','Default SETUP inventory slots assigned only when a new character is created in this world. Existing characters are not changed.','INTEGER','24','YAML_EXISTING','config.yaml','worlds[].default_setup_slots','src/main/java/config/WorldConfig.java; src/main/java/client/Character.java; src/main/java/server/configuration/ServerConfigurationOverrides.java','RESTART','SERVER_ONLY','Client-safe inventory slot cap is 96.','WORLD','MEDIUM',4,96,518),
('server.world.defaultEtcSlots','Default ETC slots','Worlds & Channels','Default ETC inventory slots assigned only when a new character is created in this world. Existing characters are not changed.','INTEGER','24','YAML_EXISTING','config.yaml','worlds[].default_etc_slots','src/main/java/config/WorldConfig.java; src/main/java/client/Character.java; src/main/java/server/configuration/ServerConfigurationOverrides.java','RESTART','SERVER_ONLY','Client-safe inventory slot cap is 96.','WORLD','MEDIUM',4,96,519),
('server.world.defaultStorageSlots','Default storage slots','Worlds & Channels','Default account storage slots created for this world when an account first opens or loads storage. Existing storage rows are not changed.','INTEGER','48','YAML_EXISTING','config.yaml','worlds[].default_storage_slots','src/main/java/config/WorldConfig.java; src/main/java/server/Storage.java; src/main/java/server/configuration/ServerConfigurationOverrides.java','RESTART','SERVER_ONLY','Existing account storage rows keep their current slot count. Current storage cap is 48.','WORLD','MEDIUM',4,48,520);
